### PR TITLE
Added AJAX (no page loading)

### PR DESCRIPTION
**Pull request by ashvathnarayanan**
image

### CODE REVIEW

**Comment by ethmtrgt** [comment]
Thanks for your pull request, you did an awesome job.
I'll review and merge it as soon as possible.
Cheers :v:

**Review by ethmtrgt — CHANGES_REQUESTED** [review]
Can you delete `.pyc` files?

**Comment by ashvathnarayanan** [comment]
> Can you delete `.pyc` files?

Yes deleted them. No pyc files left now.

**Comment by ashvathnarayanan** [comment]
Is my PR eligible for hacktoberfest?

**Comment by ethmtrgt** [comment]
> Yes deleted them. No pyc files left now.

Thank you! You did a great job.

> Is my PR eligible for hacktoberfest?

Yes, it should be.

**Review by ethmtrgt — COMMENTED** [review]
Great :+1:

**Comment by ashvathnarayanan** [comment]
Thank you very much

**Comment by ashvathnarayanan** [comment]
Hi, can you kindly add labels in the PR like these for hacktoberfest. (other repos did this for their PRs) 
image

**Comment by ethmtrgt** [comment]
Hey @ashvathnarayanan, could you check your progress on http://hacktoberfest.digitalocean.com ? In the last year it was not necessary to label PRs.

**Comment by ashvathnarayanan** [comment]
> Hey @ashvathnarayanan, could you check your progress on http://hacktoberfest.digitalocean.com ? In the last year it was not necessary to label PRs.

Yes @ethmtrgt  it is recorded there as matures in 14days, thought of being in the safer side. If its not big of a deal, I am fine.

**Comment by ethmtrgt** [comment]
Good luck 👍🍀

**Pull request merged**
